stages:
  - build
  - release
  - deploy

variables:
  assembly_extension: "dll"

compilation:
  stage: build
  before_script:
    - nuget restore
  script:
    - msbuild /p:VersionAssembly=$env:CI_COMMIT_TAG /p:Configuration=Release $env:CI_PROJECT_NAME.sln
  after_script:
    - (Get-FileHash $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION -Algorithm SHA1).Hash > $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION.sha1
  artifacts:
    paths:
      - $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION
      - $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION.sha1
    expire_in: 1 hour

# This needs to be changed by GitLab
# Release creation should be 'keyword based'
release:
  stage: release
  only: 
    - tags
  script: 
    # Create a release for the current tag
    - CreateRelease
    # Update "latest" release name the newest version number
    - UpdateLatestRelease


# This needs to be changed by GitLab
# Release creation should be 'keyword based'
release_qa:
  stage: deploy
  only: 
    - tags
  script: 
    # Update "qa" release name the newest version number
    - UpdateLatestRelease
  environment: qa
  only:
    - qa

# This needs to be changed by GitLab
# Release creation should be 'keyword based'
release_production:
  stage: deploy
  only: 
    - tags
  script: 
    # Update "production" release name the newest version number
    - UpdateLatestRelease
  environment: production
  when: manual
  only:
    - master